{{ if .Values.applications.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  # todo: annotations
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: {{ .Values.applications.certManager.namespace }}
  # todo: annotations
spec:
  isCA: true
  duration: 87600h0m0s # 10 years
  secretName: istio-ca
  commonName: istio-ca
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  subject:
    organizations:
      - cluster.local
      - cert-manager
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-ca
  # todo: annotations
spec:
  ca:
    secretName: istio-ca
{{ end }}
