{{ if and (or .Values.services.istio.enabled (eq .Values.network.type "istio")) .Values.services.argocd.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-virtual-service
  namespace: {{ .Values.services.argocd.namespace }}
  # todo: annotations
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
spec:
  hosts:
    - # todo: base on service + environment + region + domain
  gateways:
    - {{ .Values.services.istio.gateway.namespace }}/argocd-ingress-gateway
  http:
    - route:
        - destination:
            host: argo-cd-argocd-server.argocd.svc.cluster.local
            port:
              number: 80
{{ end }}