{{ if or .Values.applications.istio.enabled (eq .Values.network.mode "istio") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Values.applications.istio.istiod.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  mtls:
    mode: PERMISSIVE
{{ end }}
