{{ if .Values.applications.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: {{ .Values.applications.promtail.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.argocd.namespace }}
  project: {{ .Values.project.name }}
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: {{ .Values.applications.promtail.revision }}
    helm:
      valuesObject:
        {{ include "app-of-apps.valuesObjectPromtail" . | nindent 16 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
