{{ if and (or .Values.applications.istio.enabled (eq .Values.network.mode "istio")) .Values.applications.argocd.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-ingress-gateway
  namespace: {{ .Values.applications.istio.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-120"
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - argocd.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - argocd.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: argocd-server-tls
{{ end }}
