apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: v5.38.1
  releaseName: argocd
  namespace: argocd
  includeCRDs: true
