apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: 1.11.0
  defaultBrokerClass: Kafka

  config:
    default-ch-webhook:
      default-ch-config: |
        clusterDefault:
          # todo
        namespaceDefaults:
          # todo

    config-br-default-channel:
      channel-template-spec: |
        # todo
