{{ if and (or .Values.applications.istio.enabled (eq .Values.network.mode "istio")) .Values.applications.prometheus.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-virtual-service
  namespace: {{ .Values.applications.prometheus.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-110"
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
spec:
  hosts:
    - grafana.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
  gateways:
    - {{ .Values.applications.istio.gateway.namespace }}/grafana-ingress-gateway
  http:
    - route:
        - destination:
            host: kube-prometheus-grafana.kube-prometheus.svc.cluster.local
            port:
              number: 80
{{ end }}
